apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: production
spec:
  serviceName: "mysql-headless"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: init-mysql-config
        image: mysql:8.0
        command: ["bash", "/scripts/init-config.sh"]
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
        - name: conf-dir
          mountPath: /mnt/conf.d

      containers:
      - name: mysql
        image: mysql:8.0
        envFrom:
        - secretRef:
            name: mysql-secrets
        env:
        - name: MYSQL_DATABASE
          value: "laravel"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: conf-dir
          mountPath: /etc/mysql/conf.d
        - name: scripts-volume
          mountPath: /docker-entrypoint-initdb.d/setup-replication.sh
          subPath: setup-replication.sh

      volumes:
      - name: scripts-volume
        configMap:
          name: mysql-scripts
      - name: conf-dir
        emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 2Gi