apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-backend
  namespace: production
spec:
  replicas: 4
  selector:
    matchLabels:
      app: laravel-backend
  template:
    metadata:
      labels:
        app: laravel-backend
    spec:
      imagePullSecrets:
      - name: regcred

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role
                operator: In
                values:
                - worker

      initContainers:
      - name: run-migrations
        image: moopsdev/my-laravel-app:latest
        command: ["php", "artisan", "migrate", "--force"]
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD

      containers:
      - name: laravel-api
        image: moopsdev/my-laravel-app:latest
        ports:
        - containerPort: 9000
          name: http
        
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: APP_KEY