apiVersion: v1
kind: Service
metadata:
  name: laravel-backend-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: laravel-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000