apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: production

data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtb29wc2RldiIsInBhc3N3b3JkIjoibWVnb2hqOTg3MjAiLCJhdXRoIjoiYlc5dmNITmtaWFk2YldWbmIyaHFPVGczTWpBPSJ9fX0=
  