apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: production
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0
  MYSQL_USER: bGFyYXZlbA==
  MYSQL_PASSWORD: c2VjcmV0
  APP_KEY: YmFzZTY0OnFOL1hYWm1yVXRZamRDTWdrZzl3bjZjTGJzWXcwUzFxMytnU2g4SmNoWnM9